name: Build Test Artifact

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: hello-build
          path: dist/
